"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import HeaderComponent from "./Component/Header/page";
import {
  Layout,
  Menu,
  Row,
  Col,
  Button,
  Modal,
  Select,
  Input,
  Avatar,
  Dropdown,
  Form,
} from "antd";

const { Content, Footer } = Layout;
// const { Option } = Select;
const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <HeaderComponent />
          <Content style={{ padding: "0 50px" }}>{children}</Content>
          <Footer style={{ textAlign: "center" }}>
            Your Footer Content Here
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
